config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#index"
  resources :users do
    resources :posts do
      resources :comments, :likes
    end
  end

  namespace :api do
    resources :users do
      resources :posts do
        resources :comments
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :create, Post, :all
      can :destroy, Post, author_id: user.id
      can :create, Comment, :all
      can :destroy, Comment, author_id: user.id
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_comments_counter
  after_destroy :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end

  def as_json(options = {})
    super({ only: %i[text author_id post_id] }.merge(options))
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  has_many :likes, foreign_key: 'post_id', dependent: :destroy

  validates :title, presence: true, length: { in: 1..250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter
  after_destroy :update_posts_counter

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  public

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def as_json(options = {})
    super({ only: %i[title text] }.merge(options))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true, length: { in: 1..250 }
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @post = Post.find(request.params['post_id'])
    render json: @post.comments.all
  end

  def create
    @user = User.find(comment_params[:author_id])
    @post = Post.find(comment_params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.post_id = @post.id
    if @comment.save
      render json: { status: 'Comment created successfully!' }, status: :created
    else
      render json: { errors: @comment.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:author_id, :post_id, :text)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    @user = User.find(request.params['user_id'])
    render json: @user.posts.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email, :encrypted_password)
    end

    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comment = Comment.new(comment_params)

    @comment.author = current_user
    @comment.post = @user.posts.find(params['post_id'])
    respond_to do |f|
      if @comment.save
        f.html { redirect_to user_post_path(@user, @post) }
      else
        f.html { render :new }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id]).destroy
    respond_to do |f|
      f.html { redirect_to user_posts_path(current_user), notice: 'The Comment has been destroyed successfully' }
    end
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(like_params)

    @like.author = current_user
    respond_to do |f|
      f.html { redirect_back(fallback_location: root_path) } if @like.save
    end
  end

  def like_params
    params.permit(:author_id, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments, :author)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.author = current_user
    @post.comments_counter = 0
    @post.likes_counter = 0

    respond_to do |f|
      if @post.save
        f.html { redirect_to user_posts_path }
      else
        f.html { render :new }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id]).destroy
    respond_to do |f|
      f.html { redirect_to user_posts_path(current_user), notice: 'The Post has been destroyed successfully' }
    end
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/api/comments_helper.rb
module Api::CommentsHelper
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="container-fluid p-3">
  <h2 class="mb-4">New Comment</h2>

  <%= form_with model: @comment, url: user_post_comments_path, class: 'row g-3' do |form| %>
    <div class="col-md-12">
      <%= form.label :comment, class: 'form-label' %>:
      <%= form.text_area :text, class: 'form-control', required: true %>
    </div>

    <div class="col-md-12">
      <%= form.submit "Submit", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/likes/new.html.erb
<h1>Likes#new</h1>
<p>Find me in app/views/likes/new.html.erb</p>

app/views/posts/_comments.html.erb
<div class="comments-container">
  <p class="comment"><%= @user.name %> : <%= comment.text %></p>
</div>

app/views/posts/_post.html.erb
<div class="post">
    <div class="post_flex">
        <h4 class="small-heading">
            Post # <%= "#{post.id}"%>
        </h4>
        <p class="comment-heading">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
        
        <%if can? :destroy, post %>
          <%= button_to "Delete Post", 
              user_post_path(post.author,post), 
              method: :delete, 
              data: { turbo_confirm: "Are you sure?" },
              class: "btn btn-danger p-1" %>
          <% end %>
    </div>
    <p><%= @post.title %></p>
    <p><%= @post.text %></p>
</div>

app/views/posts/index.html.erb
<div class="container-fluid p-3">
  <div class="row">
    <div class="col-md-12">
      <%= render('users/user_intro', user: @user) %>
    </div>
    <div class="col-md-12">
      <% @posts.each do |post| %>
      <div class="card mb-3">
        <div class="card-body">
          <%= link_to user_post_path(@user, post), class: 'text-decoration-none' do %>
          <h5 class="card-title fw-bold mb-3"><%= post.title %></h5>
          <p class="card-text mb-3"><%= post.text %></p>
            <div class="text-end">
            <p class="card-text mb-3">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
            </div>
          <% end %>
          <div class="text-end">
          <%if can? :destroy, post %>
          <%= button_to "Delete Post", 
              user_post_path(post.author,post), 
              method: :delete, 
              data: { turbo_confirm: "Are you sure?" },
              class: "btn btn-danger" %>
          <% end %>
          </div>
          <div>
            <h5 class="card-title fw-bold mb-3">Comments</h5>
            <% post.recent_comments.each do |comment| %>
              <p><strong><%= comment.author.name %> :</strong> <%= comment.text %></p>
            <div class="text-end">
            <% if can? :destroy, comment %>
              <%= button_to "Delete Comment", 
                  user_post_comment_path(comment.author_id, comment.post_id, comment), 
                  method: :delete, 
                  data: { turbo_confirm: "Are you sure?" }, 
                  class: "btn btn-danger" %>
            <% end %>
            </div>           
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
      <div class="d-flex justify-content-center mt-3">
        <button class="btn btn-primary">Pagination</button>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container-fluid p-3">
<h2 class="mb-4">New Post</h2>

<%= form_with model: @post, url: user_posts_path, class: 'row g-3' do |form| %>
  <div class="col-md-12">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="col-md-12">
    <%= form.label :text, class: 'form-label' %>
    <%= form.text_area :text, class: 'form-control', rows: 8 %>
  </div>

  <div class="col-md-12">
    <%= form.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="container-fluid p-3">
  <div class="row">
    <div class="col-md-12">
      <div>
        <h4><%= @post.title %> by <%= @user.name %></h4>
        <div class="text-end mb-3">
          <p>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
        </div>
        <p><%= @post.text %></p>
      </div>
      <div class="comments">
        <% @post.comments.each do |comment| %>
          <div class="card mb-3">
            <div class="card-body">
             <p><strong><%= comment.author.name %> :</strong> <%= comment.text %></p>
            </div>
          </div>
        <% end %>
      </div>
      <div class="d-flex justify-content-center mb-3">
          <%= form_with model: Like.new, url: user_post_likes_path(@user, @post), class: "me-2" do |form| %>
            <div class="d-grid">
              <%= form.submit "Like", class: "btn btn-primary" %>
            </div>
          <% end %>
        <%= link_to('Add New Comment', new_user_post_comment_path(@user, @post), class: 'btn btn-primary btn-custom') %>
      </div>
    </div>
  </div>
</div>

app/views/users/_bio.html.erb
<div class="bio">
  <h4>Bio</h4>
  <p><%= @user.bio %></p>
</div>

app/views/users/_post.html.erb
<li class="post_er">
    <h4 class="small-heading">
        <%= link_to "Post ##{post.id}", user_post_path(post.author_id, post.id) %>
    </h4>
    <p><%= post.text %></p>
    <p class="comment-heading">Comments: <%= post.comments_counter%>, Likes: <%= post.likes_counter %></p>
</li>

app/views/users/_user.html.erb
<li class="user_card">
    <div class="image_container">
      <img class="image" src="<%= user.photo %>" alt="<%= user.name %>" >
    </div>
    <div class="details_card">
        <div class="heading-container">
            <h4 class="user_name">
            <%= link_to user.name, user_path(user.id) %>
            </h4>
        </div>
        <div class="counter">
        <p>Number of posts: <%= user.posts.count %></p>
        </div>
    </div>
</li>

app/views/users/_user_intro.html.erb
<div class="container-fluid">
  <div class="card mb-3">
    <div class="row">
      <div class="col-md-4">
        <img src="<%= user.photo ? user.photo : 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Default_pfp.jpg' %>" alt="<%= user.name %>" class="card-img" style="width: 40%">
      </div>
      <div class="col-md-4">
        <div class="card-body">
          <h2 class="card-title fw-bold" style="color: black"><%= user.name %></h2>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card-body">
          <p class="card-title mt-3 fw-bold" style="color: black">Number of posts: <%= user.posts_counter %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container-fluid p-3">
    <h1 class="text-center fw-bold">Users List</h1>
    <ul class="list-group">
        <% @users.order(id: :asc).each do |user| %>
            <li><%= link_to(render('user_intro', user: user), user_path(user)) %></li>
        <% end %>
    </ul>
</div>

app/views/users/show.html.erb
<div class="container-fluid p-3">
  <div class="row">
    <div class="col-md-12">
      <%= render('user_intro', user: @user) %>
    </div>
    <div class="col-md-12">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title fw-bold">Bio</h5>
          <p class="card-text"><%= @user.bio %></p>
        </div>
      </div>
      <div class="d-flex justify-content-center mb-3">
        <%= link_to('Add New Post', new_user_post_path(@user), class: 'btn btn-primary btn-custom') %>
      </div>
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title fw-bold">Recent Posts</h5>
          <% @user.recent_posts.each do |post| %>
          <div class="mb-3">
            <h6 class="card-subtitle mb-2 text-muted"><%= post.title %></h6>
            <p class="card-text"><%= post.text %></p>
            <p class="card-text text-end mb-3">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
          </div>
          <% end %>
          <div class="d-flex justify-content-center mt-3">
            <%= link_to('See all posts', user_posts_path(@user), class: 'btn btn-primary btn-custom') %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>